services:
  - type: web
    name: engagement-tracker
    env: python
    region: singapore
    buildCommand: |
      apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0
      pip install --no-cache-dir --upgrade pip
      pip install --no-cache-dir -r requirements.txt

    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app --bind 0.0.0.0:8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PATH
        value: "/usr/local/bin:/usr/bin:/bin"
    autoDeploy: true
    healthCheckPath: /health
